# Generated by Django 3.0.5 on 2020-04-26 08:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gross_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.Invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Invoice Entry',
                'verbose_name_plural': 'Invoice Entries',
            },
        ),
    ]
