# Generated by Django 3.0.5 on 2020-04-26 08:45

from decimal import Decimal
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTSlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('cess', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'GST Slab',
                'verbose_name_plural': 'GST Slabs',
            },
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Unit of measure',
                'verbose_name_plural': 'Units of measure',
            },
        ),
    ]
