# Generated by Django 3.0.5 on 2020-04-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0002_auto_20200418_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BetaSubscription',
            new_name='Subscription',
        ),
    ]
