# Generated by Django 3.0.5 on 2020-04-25 07:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import invoice_101.contact.utils
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=invoice_101.contact.utils.get_contact_image_path)),
                ('is_customer', models.BooleanField(default=True)),
                ('is_supplier', models.BooleanField(default=True)),
                ('billing_address_line_1', models.CharField(blank=True, max_length=512, null=True)),
                ('billing_address_line_2', models.CharField(blank=True, max_length=512, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_pin_code', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Invalid PinCode.')])),
                ('shipping_address_line_1', models.CharField(blank=True, max_length=512, null=True)),
                ('shipping_address_line_2', models.CharField(blank=True, max_length=512, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_pin_code', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Invalid PinCode.')])),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}[a-zA-Z]{5}\\d{4}[a-zA-Z][a-zA-Z\\d][zZ][a-zA-Z\\d]$', 'Invalid GST.')])),
                ('billing_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_billing_state', to='core.State')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipping_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_shipping_state', to='core.State')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
