# Generated by Django 3.0.5 on 2020-05-01 07:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_gstslab_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_percentage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.GSTSlab')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.UOM')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
